import { SectionHeader } from "@/components/ui/SectionHeader";

/**
 * Compose takeaway preview — shows the pinned-by-digest YAML that
 * flareo compose outputs. Load-bearing for the "Takeaway" hero pillar.
 */
export function ComposePreview() {
  return (
    <section className="border-b border-hairline px-8 py-14">
      <SectionHeader
        num="06"
        label="THE TAKEAWAY"
        title="You leave with a docker-compose.yaml, pinned to a digest."
      >
        No lock-in, no Flareo runtime on your box. The output of{" "}
        <span className="text-ink">flareo compose</span> is plain YAML with
        the image reference pinned to the exact signed sha256 digest you
        just verified. Run it anywhere Docker runs.
      </SectionHeader>

      <div className="overflow-hidden border border-hairline bg-canvas-deep">
        <div className="flex items-center justify-between border-b border-hairline bg-canvas-panel px-4 py-3 font-mono text-[11px] tracking-[0.04em] text-ink-faint">
          <div className="flex items-center gap-3">
            <div className="flex gap-[5px]">
              <span className="block h-2 w-2 rounded-full bg-accent" />
              <span className="block h-2 w-2 rounded-full bg-hairline-soft" />
              <span className="block h-2 w-2 rounded-full bg-hairline-soft" />
            </div>
            <span>docker-compose.yaml · generated by flareo compose vaultwarden</span>
          </div>
          <span className="text-ink-ghost">copy →</span>
        </div>
        <pre className="overflow-x-auto p-5 font-mono text-[12.5px] leading-[1.8] text-ink-mute">
{`# Generated by flareo 0.4.2 · 2026-04-21T14:05:14Z
# Module: vaultwarden@1.30.5 · SLSA L3 · 0 CVEs
# Verify: cosign verify ghcr.io/flareo/vaultwarden@sha256:9a8b7c6d5e4f
version: "3.9"

services:
  vaultwarden:
    image: `}<span className="text-accent">ghcr.io/flareo/vaultwarden@sha256:9a8b7c6d5e4f3a2b</span>{`
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: `}<span className="text-warn">&quot;https://vault.example.com&quot;</span>{`
      SIGNUPS_ALLOWED: `}<span className="text-warn">&quot;false&quot;</span>{`
      WEBSOCKET_ENABLED: `}<span className="text-warn">&quot;true&quot;</span>{`
    ports:
      - `}<span className="text-warn">&quot;8080:80&quot;</span>{`
      - `}<span className="text-warn">&quot;3012:3012&quot;</span>{`
    volumes:
      - ./vw-data:/data
    labels:
      flareo.module: vaultwarden
      flareo.version: `}<span className="text-warn">&quot;1.30.5&quot;</span>{`
      flareo.slsa: L3
      flareo.verified-at: `}<span className="text-warn">&quot;2026-04-20T14:05:14Z&quot;</span>
        </pre>
      </div>
    </section>
  );
}
