/**
 * Frozen walkthrough for /pipeline.
 *
 * One recorded republish of Vaultwarden. Every visitor sees the same
 * screens, the same digest, the same receipts. This is a demonstration
 * of how the pipeline works — not a live pull, not a live sign.
 *
 * The product this traces:
 *   pin upstream → retag (byte-identical) → SBOM → Trivy + VEX →
 *   cosign keyless + Rekor → catalog row → anyone verifies.
 *
 * It does not build from a Dockerfile and it does not claim an SLSA
 * build level. Those paths were retired.
 */

export const DEMO_STEPS = [
  { id: "pin", num: "01", label: "Pin" },
  { id: "republish", num: "02", label: "Republish" },
  { id: "sbom", num: "03", label: "SBOM" },
  { id: "scan", num: "04", label: "Scan" },
  { id: "sign", num: "05", label: "Sign" },
  { id: "catalog", num: "06", label: "Catalog" },
  { id: "verify", num: "07", label: "Verify" },
] as const;

export type DemoStepId = (typeof DEMO_STEPS)[number]["id"];

export const DEMO_RUN = {
  runId: "FLA-DEMO-0001",
  recordedAt: "2026-08-11T14:02:00Z",
  durationLabel: "4m 12s",
  module: {
    slug: "vaultwarden",
    name: "Vaultwarden",
    version: "1.32.7",
    author: "dani-garcia",
    description: "Bitwarden-compatible password manager in Rust.",
    size: "62 MB",
    trust: 99,
    catalogHref: "/modules/vaultwarden",
  },
  upstream: {
    ref: "docker.io/vaultwarden/server:1.32.7",
    digest:
      "sha256:c8f3e91a7b4d2e6f0a1c5b8d9e3f7a2c4b6d8e0f1a3c5b7d9e1f3a5c7b9d0e2f",
  },
  published: {
    ref: "public.ecr.aws/flareo/vaultwarden:1.32.7",
    digest:
      "sha256:c8f3e91a7b4d2e6f0a1c5b8d9e3f7a2c4b6d8e0f1a3c5b7d9e1f3a5c7b9d0e2f",
  },
  sbom: {
    format: "CycloneDX",
    specVersion: "1.5",
    tool: "syft 1.14.0",
    packagesIndexed: 210,
    serialNumber: "urn:uuid:7e2c1a90-4b3d-4e8f-9a1c-6d5e4f3a2b1c",
    components: [
      {
        name: "debian",
        version: "12.5",
        type: "operating-system",
        purl: "pkg:deb/debian/debian@12.5",
      },
      {
        name: "vaultwarden",
        version: "1.32.7",
        type: "application",
        purl: "pkg:generic/vaultwarden@1.32.7",
      },
      {
        name: "openssl",
        version: "3.0.13",
        type: "library",
        purl: "pkg:deb/debian/openssl@3.0.13",
      },
      {
        name: "ca-certificates",
        version: "20230311",
        type: "library",
        purl: "pkg:deb/debian/ca-certificates@20230311",
      },
    ],
  },
  scan: {
    scanner: "trivy 0.54.1",
    scanTimeMs: 3120,
    summary: { critical: 0, high: 0, medium: 1, low: 3 },
    findings: [
      {
        cve: "CVE-2024-5535",
        pkgName: "openssl",
        installedVersion: "3.0.13",
        severity: "MEDIUM" as const,
        title: "SSL_select_next_proto buffer overread",
      },
    ],
    vex: {
      cve: "CVE-2024-5535",
      status: "not_affected" as const,
      justification: "vulnerable_code_not_in_execute_path",
      statement:
        "Vaultwarden does not call SSL_select_next_proto. OpenVEX marks this finding not_affected so admission policy can ignore it.",
    },
  },
  signature: {
    identity:
      "https://github.com/Yolo1105/flareo/.github/workflows/republish.yml@refs/heads/main",
    issuer: "https://token.actions.githubusercontent.com",
    rekorLogIndex: "14829331",
    rekorUrl: "https://search.sigstore.dev/?logIndex=14829331",
    integratedAt: "2026-08-11T14:06:09Z",
  },
  trust: {
    total: 99,
    parts: [
      {
        label: "Vulnerability posture",
        value: 40,
        max: 40,
        note: "0 critical, 0 high after VEX",
      },
      {
        label: "Provenance",
        value: 25,
        max: 25,
        note: "upstream digest recorded and equal",
      },
      {
        label: "Signature",
        value: 20,
        max: 20,
        note: "cosign keyless · Rekor logged",
      },
      {
        label: "SBOM",
        value: 14,
        max: 15,
        note: "CycloneDX 1.5 · 210 components",
      },
    ],
  },
  compose: `# Generated by flareo — pinned to the verified digest
# vaultwarden 1.32.7 · trust 99 · recorded demo run FLA-DEMO-0001
services:
  vaultwarden:
    image: public.ecr.aws/flareo/vaultwarden@sha256:c8f3e91a7b4d2e6f0a1c5b8d9e3f7a2c4b6d8e0f1a3c5b7d9e1f3a5c7b9d0e2f
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8222:80"
    volumes:
      - vw-data:/data

volumes:
  vw-data:

# Verify before you pull:
#   flareo verify public.ecr.aws/flareo/vaultwarden:1.32.7
`,
} as const;

export type DemoRun = typeof DEMO_RUN;

export function shortDigest(digest: string, chars = 16): string {
  const hex = digest.replace(/^sha256:/, "");
  return `sha256:${hex.slice(0, chars)}…`;
}
