import type { Module } from "@/lib/types";
import { formatLastRebuiltAt } from "@/lib/utils/time";

/**
 * Per-module deployment artifact generators ("takeaway").
 *
 * Extracted from DeploySection so the API route at
 * /api/v1/modules/[slug]/takeaway can render the same four artifacts
 * for download. Both surfaces stay in sync because they call the same
 * functions.
 *
 * The generators produce real-syntax artifacts — compose YAML that
 * parses, Helm values that match the chart shape we'd publish, an
 * .env that matches upstream config keys, a docker run that runs.
 * Per-category specialization (port, volumes, env keys) ensures
 * different modules produce meaningfully different artifacts rather
 * than generic templates.
 *
 * The proposal called this section "what you walk away with" — the
 * artifacts ARE the no-lock-in proof, so they can't be hello-world.
 */

export interface TakeawayBundle {
  /** docker-compose.yaml content */
  compose: string;
  /** Helm values.yaml content */
  helm: string;
  /** .env content */
  env: string;
  /** docker run shell command */
  run: string;
  /** README.md describing the bundle */
  readme: string;
}

interface EnvKey {
  /** Local-environment variable name (e.g. ADMIN_TOKEN) */
  envVar: string;
  /** Container-side key (often differs, e.g. GF_SECURITY_ADMIN_USER) */
  key: string;
  /** One-line description for documentation */
  description: string;
  /** Placeholder value */
  placeholder: string;
}

// ─── public generators ────────────────────────────────────────────

export function generateCompose(m: Module): string {
  const port = portFor(m);
  const volumes = volumesFor(m);
  const envSection = envKeysFor(m)
    .map((k) => `      ${k.key}: \${${k.envVar}}`)
    .join("\n");

  return `# Generated by flareo 0.4.2 — pinned to verified digest
# ${m.name} v${m.version} · trust ${m.trust}/100 · signed provenance
version: "3.9"

services:
  ${m.slug}:
    image: ghcr.io/flareo/${m.slug}@${m.digest}
    container_name: ${m.slug}
    restart: unless-stopped
    ports:
      - "${port}:${port}"
    volumes:
${volumes.map((v) => `      - ${v}`).join("\n")}
    environment:
${envSection}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${port}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

# Verify the image before pulling:
#   cosign verify ghcr.io/flareo/${m.slug}@${m.digest.slice(0, 19)}…
#   --certificate-identity 'https://github.com/Yolo1105/flareo/.github/workflows/canary-rebuild.yml@refs/heads/main'
#   --certificate-oidc-issuer 'https://token.actions.githubusercontent.com'`;
}

export function generateHelmValues(m: Module): string {
  const port = portFor(m);
  const env = envKeysFor(m);
  return `# values.yaml — pin to the digest, not a mutable tag
# ${m.name} v${m.version} · trust ${m.trust}/100 · signed provenance

image:
  repository: ghcr.io/flareo/${m.slug}
  digest: "${m.digest}"
  pullPolicy: IfNotPresent

verification:
  # Flareo emits these for every published module. Enable
  # cosign verification at admission time using the snippet at
  # /docs/admission.
  cosign:
    enabled: true
    issuer: "https://token.actions.githubusercontent.com"
    identity: "https://github.com/Yolo1105/flareo/.github/workflows/canary-rebuild.yml@refs/heads/main"
  provenance: ${m.trustBreakdown.provenance}
  sbomDownload: "ghcr.io/flareo/${m.slug}/sbom"

service:
  type: ClusterIP
  port: ${port}
  targetPort: ${port}

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: ${m.slug}.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: ""
  size: 8Gi
  accessMode: ReadWriteOnce

env:
${env.map((k) => `  ${k.envVar}: ""  # ${k.description}`).join("\n")}

# Install with:
#   helm install ${m.slug} flareo/${m.slug} -f values.yaml`;
}

export function generateEnv(m: Module): string {
  const env = envKeysFor(m);
  return `# .env for ${m.name} v${m.version}
# Copy this file, fill in the values, never check it into git.
# Flareo doesn't mint these for you — they go where the documented
# upstream config goes (volumes, secrets manager, K8s Secret, etc).

${env
  .map(
    (k) =>
      `# ${k.description}\n${k.envVar}=${k.placeholder}`,
  )
  .join("\n\n")}

# Flareo metadata — for your own audit trail
FLAREO_MODULE=${m.slug}
FLAREO_VERSION=${m.version}
FLAREO_DIGEST=${m.digest}
FLAREO_TRUST_SCORE=${m.trust}
FLAREO_PROVENANCE=${m.trustBreakdown.provenance}`;
}

export function generateRun(m: Module): string {
  const port = portFor(m);
  const env = envKeysFor(m);
  const envFlags = env
    .map((k) => `  -e ${k.envVar}="$${k.envVar}" \\`)
    .join("\n");
  return `# Single command — no compose, no Helm.
docker run -d \\
  --name ${m.slug} \\
  --restart unless-stopped \\
  -p ${port}:${port} \\
  -v $(pwd)/data:/data \\
${envFlags}
  ghcr.io/flareo/${m.slug}@${m.digest}

# Then verify it's running:
#   docker logs ${m.slug}
#   curl http://localhost:${port}/health`;
}

/**
 * README that ships inside the takeaway bundle. Explains what each
 * file is for and the verify-yourself path.
 */
export function generateReadme(m: Module): string {
  return `# ${m.name} v${m.version} — Flareo takeaway bundle

This bundle was generated by Flareo for module \`${m.slug}\`. It contains
four files for running this module on your own infrastructure:

  docker-compose.yaml  # paste into any Docker Compose stack
  values.yaml          # Helm values.yaml fragment for k8s deploys
  .env                 # configuration knobs
  run.sh               # single docker run command, no orchestrator

Every file references the verified sha256 digest, not a mutable tag —
so even if upstream repoints \`:latest\` tomorrow, your deploy stays on
the exact image you trusted.

## Verify before you deploy

You don't have to trust Flareo's word that this image is signed. Run
the cosign verify locally yourself:

    cosign verify ghcr.io/flareo/${m.slug}@${m.digest} \\
      --certificate-identity 'https://github.com/Yolo1105/flareo/.github/workflows/canary-rebuild.yml@refs/heads/main' \\
      --certificate-oidc-issuer 'https://token.actions.githubusercontent.com'

You can also pull the SBOM and Trivy scan:

    cosign download sbom ghcr.io/flareo/${m.slug}@${m.digest}
    cosign download attestation --type vuln ghcr.io/flareo/${m.slug}@${m.digest}

## Module attestations

Trust score:    ${m.trust}/100
Provenance:     ${m.trustBreakdown.provenance}/100 (signed provenance, upstream digest recorded)
Critical CVEs:  ${m.cves.critical}
High CVEs:      ${m.cves.high}
Image size:     ${m.size}
Last rebuild:   ${
  m.lastRebuiltAt
    ? formatLastRebuiltAt(m.lastRebuiltAt)
    : "not yet republished"
}

## No lock-in by design

These files run anywhere — your VPS, your Kubernetes cluster, a homelab
NUC, an air-gapped lab. Flareo is not in your runtime path after you
copy them out. If Flareo shut down tomorrow, this bundle still works
because the image is in ghcr.io and the signature is in public Rekor.

## Reading list

  /modules/${m.slug}                 — module detail page on Flareo
  /modules/${m.slug}#receipts        — full attestation chain
  /docs/trust-score                  — methodology behind the score
  /pipeline?module=${m.slug}         — every pipeline stage walkthrough
`;
}

/**
 * Render all four artifacts plus the README.
 */
export function generateTakeawayBundle(m: Module): TakeawayBundle {
  return {
    compose: generateCompose(m),
    helm: generateHelmValues(m),
    env: generateEnv(m),
    run: generateRun(m),
    readme: generateReadme(m),
  };
}

// ─── per-category helpers ─────────────────────────────────────────

function portFor(m: Module): number {
  switch (m.category) {
    case "auth":
      return 9000;
    case "monitoring":
      return 3000;
    case "media":
      return 2283;
    case "security":
      return 80;
    default:
      return 8080;
  }
}

function volumesFor(m: Module): string[] {
  switch (m.category) {
    case "auth":
      return ["./data:/data", "./config:/etc/config:ro"];
    case "monitoring":
      return ["./data:/data", "./grafana:/var/lib/grafana"];
    case "media":
      return ["./photos:/usr/src/app/upload", "./database:/usr/src/app/database"];
    default:
      return ["./data:/data"];
  }
}

function envKeysFor(m: Module): EnvKey[] {
  switch (m.category) {
    case "auth":
      return [
        {
          envVar: "ADMIN_TOKEN",
          key: "ADMIN_TOKEN",
          description: "Admin API token for setup. Rotate after install.",
          placeholder: "change_me_to_a_64_byte_random",
        },
        {
          envVar: "DOMAIN",
          key: "DOMAIN",
          description: "Public domain this instance is reachable at.",
          placeholder: "auth.example.com",
        },
        {
          envVar: "SMTP_HOST",
          key: "SMTP_HOST",
          description: "SMTP server for password reset emails.",
          placeholder: "smtp.example.com",
        },
      ];
    case "monitoring":
      return [
        {
          envVar: "ADMIN_USER",
          key: "GF_SECURITY_ADMIN_USER",
          description: "Initial admin login.",
          placeholder: "admin",
        },
        {
          envVar: "ADMIN_PASSWORD",
          key: "GF_SECURITY_ADMIN_PASSWORD",
          description: "Initial admin password. Change at first login.",
          placeholder: "change_me_at_first_login",
        },
      ];
    case "media":
      return [
        {
          envVar: "DB_HOSTNAME",
          key: "DB_HOSTNAME",
          description: "Postgres hostname for media metadata.",
          placeholder: "postgres",
        },
        {
          envVar: "JWT_SECRET",
          key: "JWT_SECRET",
          description: "JWT signing secret. 64 random bytes recommended.",
          placeholder: "openssl_rand_hex_64",
        },
      ];
    default:
      return [
        {
          envVar: "ADMIN_TOKEN",
          key: "ADMIN_TOKEN",
          description: "Admin token for initial setup.",
          placeholder: "change_me",
        },
      ];
  }
}
