import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { shapeToModule, type ModuleShape } from "@/lib/db/queries";
import { apiError } from "@/lib/validation/schemas";
import { generateTakeawayBundle } from "@/lib/data/takeaway";
import { appBaseUrl } from "@/lib/config/env";

/**
 * GET /api/v1/modules/[slug]/takeaway
 *
 * Returns a single text file ("takeaway.md") containing all four
 * deployment artifacts (docker-compose.yaml, values.yaml, .env, the
 * docker run command) plus a README explaining what's in the bundle
 * and how to verify the image before deploying.
 *
 * Why a single .md instead of a tarball?
 *
 *   - No archive library dependency to install or maintain
 *   - Universally readable; works in browser, terminal, IDE, paste-bin
 *   - Easy to copy individual sections
 *   - Renders well in editors and on GitHub / Gist
 *
 * The format uses markdown code fences with language hints so the
 * content remains parseable by tooling — `flareo takeaway --extract`
 * (planned for the CLI roadmap) splits it back into the four files.
 *
 * Available without auth — this endpoint is the engineering side of
 * the proposal's "no lock-in" content claim. A consumer being able
 * to download the artifacts before signing up is the whole point.
 *
 * Rate-limited as a normal anonymous request via Cache-Control rather
 * than per-IP; the response is fully cacheable for 5 minutes since
 * the artifacts are deterministic per module digest.
 */
export const runtime = "nodejs";

interface Ctx {
  params: Promise<{ slug: string }>;
}

export async function GET(_req: NextRequest, ctx: Ctx) {
  const { slug } = await ctx.params;

  if (!slug || !/^[a-z0-9][a-z0-9-]{0,63}$/.test(slug)) {
    return NextResponse.json(
      apiError("invalid_slug", "module slug must be lowercase alphanumeric with hyphens"),
      { status: 400 },
    );
  }

  let row: ModuleShape | null;
  try {
    row = (await prisma.module.findUnique({
      where: { slug } as never,
    })) as ModuleShape | null;
  } catch {
    return NextResponse.json(
      apiError("db_error", "could not look up module"),
      { status: 503 },
    );
  }

  if (!row) {
    return NextResponse.json(
      apiError("not_found", `no module found with slug "${slug}"`),
      { status: 404 },
    );
  }

  const mod = shapeToModule(row);

  // Skip private modules — takeaway is for public modules only.
  // Private-module owners get their own download via the publisher
  // dashboard which carries auth.
  if (mod.visibility !== "public") {
    return NextResponse.json(
      apiError("forbidden", "takeaway bundles for private modules are only available to the publisher"),
      { status: 403 },
    );
  }

  const bundle = generateTakeawayBundle(mod);

  // Compose the single-file artifact. Markdown code fences with
  // language hints so content is renderable everywhere AND
  // programmatically extractable by language tag.
  const content = [
    bundle.readme,
    "",
    "---",
    "",
    "## docker-compose.yaml",
    "",
    "```yaml",
    bundle.compose,
    "```",
    "",
    "## values.yaml",
    "",
    "```yaml",
    bundle.helm,
    "```",
    "",
    "## .env",
    "",
    "```ini",
    bundle.env,
    "```",
    "",
    "## run.sh",
    "",
    "```bash",
    bundle.run,
    "```",
    "",
    "---",
    "",
    `Generated by Flareo on ${new Date().toISOString().slice(0, 19)}Z.`,
    `For the live module page: ${appBaseUrl()}/modules/${mod.slug}`,
  ].join("\n");

  return new NextResponse(content, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${mod.slug}-${mod.version}-takeaway.md"`,
      // Deterministic per module digest, so 5 minutes of cache
      // is safe and cuts repeat-download latency to ~0.
      "Cache-Control": "public, max-age=300, s-maxage=300",
      // The digest is the natural ETag — if the underlying module
      // is rebuilt to a new digest, the takeaway bundle changes.
      ETag: `"${mod.digest}"`,
    },
  });
}
