-- AdmissionPolicy + ModulePolicyVerdict — the OPA-shaped catalog
-- admission gate.
--
-- AdmissionPolicy:
--   - Append-only revisions table. Each save creates a new row;
--     the "active" policy is the one with the highest revision.
--   - revision is monotonic Int with a unique constraint. We rely
--     on this for the "fresh max + insert" race-safety pattern in
--     lib/db/policy.ts:savePolicy (single retry on unique-violation).
--   - notes is required at the application layer (≥5 chars). DB
--     stores TEXT to leave headroom for detailed changelog entries.
--   - authorId CASCADE: deleting an admin doesn't normally happen,
--     but if it does the audit trail goes with them. Acceptable
--     for v1; future GDPR-grade audit retention would convert to
--     SET NULL with a "deleted user" rendering in the admin UI.
--
-- ModulePolicyVerdict:
--   - One row per module (cached verdict). Upserted on policy
--     change or module rebuild.
--   - verdict denormalized to its own column for cheap aggregation
--     queries ("8 pass · 3 warn · 1 fail" on the dashboard) without
--     parsing verdictJson.
--   - moduleSlug FK CASCADE — verdict is meaningless without the
--     module it references.
--   - No FK on policyRevision: if an old revision is removed for
--     some reason, the cached verdict's revision pointer stays as
--     a number for audit. Stale verdicts get regenerated by the
--     "regenerate verdicts" admin sweep.

CREATE TABLE "AdmissionPolicy" (
  "id"          TEXT          PRIMARY KEY,
  "revision"    INTEGER       NOT NULL,
  "policyJson"  TEXT          NOT NULL,
  "notes"       TEXT          NOT NULL,
  "authorId"    TEXT          NOT NULL,
  "createdAt"   TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "AdmissionPolicy_authorId_fkey"
    FOREIGN KEY ("authorId")
    REFERENCES "User"("id")
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX "AdmissionPolicy_revision_key"
  ON "AdmissionPolicy" ("revision");

CREATE INDEX "AdmissionPolicy_authorId_idx"
  ON "AdmissionPolicy" ("authorId");

CREATE INDEX "AdmissionPolicy_createdAt_idx"
  ON "AdmissionPolicy" ("createdAt");

CREATE TABLE "ModulePolicyVerdict" (
  "id"             TEXT          PRIMARY KEY,
  "moduleSlug"     TEXT          NOT NULL,
  "verdict"        VARCHAR(8)    NOT NULL,
  "policyRevision" INTEGER       NOT NULL,
  "verdictJson"    TEXT          NOT NULL,
  "evaluatedAt"    TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "ModulePolicyVerdict_moduleSlug_fkey"
    FOREIGN KEY ("moduleSlug")
    REFERENCES "Module"("slug")
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX "ModulePolicyVerdict_moduleSlug_key"
  ON "ModulePolicyVerdict" ("moduleSlug");

CREATE INDEX "ModulePolicyVerdict_verdict_idx"
  ON "ModulePolicyVerdict" ("verdict");

CREATE INDEX "ModulePolicyVerdict_policyRevision_idx"
  ON "ModulePolicyVerdict" ("policyRevision");
